#ddev-generated

http:
  routers:
    
    
    my-site-web-80-http:
      
      rule: HostRegexp(`my-site.ddev.site`)
      
      service: "my-site-web-80-http"
      tls: false
      entrypoints:
        - http-80
    
    
    my-site-web-8025-http:
      
      rule: HostRegexp(`my-site.ddev.site`)
      
      service: "my-site-web-8025-http"
      tls: false
      entrypoints:
        - http-8025
    
    
    
    
    my-site-solr-8983-http:
      
      rule: HostRegexp(`my-site.ddev.site`)
      
      service: "my-site-solr-8983-http"
      tls: false
      entrypoints:
        - http-8983
    
    
    
    
    my-site-web-80-https:
      
      rule: HostRegexp(`my-site.ddev.site`)
      
      service: "my-site-web-80-https"
      
      tls: true
      
      entrypoints:
        - http-443
    
    
    my-site-web-8025-https:
      
      rule: HostRegexp(`my-site.ddev.site`)
      
      service: "my-site-web-8025-https"
      
      tls: true
      
      entrypoints:
        - http-8026
    
    
    

  services:
    
    my-site-web-80-http:
      loadbalancer:
        servers:
          - url: http://ddev-my-site-web:80
    
    my-site-web-8025-http:
      loadbalancer:
        servers:
          - url: http://ddev-my-site-web:8025
    
    my-site-web-80-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-my-site-web:80
    
    my-site-web-8025-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-my-site-web:8025
    
    my-site-solr-8983-http:
      loadbalancer:
        servers:
          - url: http://ddev-my-site-solr:8983
    


tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/my-site.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/my-site.key

